### ISSUE TITLE
Serilog.Settings.Configuration 

### ISSUE THREAD

**Issue by AndreBooysen** [ramonesz297/yet-another-serilog-sinks-loki#14]
Hi 

Can the configuration be done in the appsettings file in the Serilog configuration section?

If so, do you have a sample please

**Comment by ramonesz297** [comment]
@AndreBooysen Hi!

I have found some issue when binding configurations via `Serilog.Settings.Configuration`.  In v1.3.0 it should work.  I have updated README, and there is a full example in samples/
